[project]
name = "problems-with-weasyprint"
version = "1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    'pygal',
    'weasyprint==63.1',
    # 'weasyprint==64',
    'jinja2',
]
